changed the cut-off radius from int  to float so it does not overflow…
cersonsky-lab/AniSOAP pull request #39
Opened 2024-04-23 20:48 UTC by SeonwooH

… and lead to negative value

2024-04-23 20:51 UTC, arthur-lin1027 approved these changes
Looks great!

2024-04-23 20:54 UTC, arthur-lin1027 requested changes
Add some type checking in the radial_basis class. You can take the typechecking code that I've done in EllipsoidalDensityProjection and just copy it into the RadialBasis class, so typechecking occurs in both classes!
See what I did here: [https://github.com/cersonsky-lab/AniSOAP/blob/main/anisoap/representations/ellipsoidal_density_projection.py#L447-L451](url)

2024-04-23 22:43 UTC, rosecers approved these changes
Looks great!

2024-04-25 19:30 UTC, arthur-lin1027 approved these changes

2024-04-25 19:31 UTC, merged